# Generated by Django 5.1.2 on 2024-11-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_payment_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='razorpay_order_id',
        ),
    ]
