# Generated by Django 5.1.2 on 2024-11-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_razorpay_order_id_payment_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='created',
            new_name='ordered_date',
        ),
    ]
